language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: s3
  access_key_id:
  secret_access_key:
  bucket: "www.csguidebook.com"
  skip_cleanup: true
  local_dir: build
on:
  branch: master
notifications:
  email:
    on_success: never
    on_failure: always
